name: Check
description: Check the code with audit, fmt and clippy
runs:
  using: composite
  steps:
    - name: Audit
      shell: bash
      run: |
        if ! command -v cargo-audit &> /dev/null; then
          cargo install cargo-audit
        fi
        cargo install cargo-audit
        cargo audit

    - name: Fmt
      shell: bash
      run: cargo fmt --check

    - name: Clippy
      shell: bash
      # You need to run 'cargo clippy -r' in the local to get the same output with CI
      run: cargo clippy -- -D warnings
